### ISSUE TITLE
input doesnt work

### ISSUE THREAD

**Issue by tloaf** [LambdaHack/LambdaHack#290]
for some reason, with any binary, the game launches but i cant get past the "press any key to regain control" screen. its the same with allure of the stars.

**Comment by Mikolaj** [comment]
Hi! Thank you for the report. Which binaries do you mean? Could you try some older versions? What's your OS? What's your SDL library version?

**Comment by Mikolaj** [comment]
One more thing: could you try not only keyboard, but also the mouse? Could you try a commandline option that starts the game not in the mode with "press any key to regain control"?

**Comment by tloaf** [comment]
OS: linux
SDL version : 2.0.20
mouse doesnt work either
everything works fine when its run through the terminal, it seems like its the SDL window that doesnt take any inputs, including close.

**Comment by Mikolaj** [comment]
Thank you.

I wonder what they broke again in SDL. I see SDL 2.0.20 is in Debian testing (https://packages.debian.org/bookworm/libsdl2-2.0-0 and Ubuntu 22.04, so it should soon be available to ordinary users. I guess I won't be able to debug until then.

Any help is kindly welcome.

**Comment by Mikolaj** [comment]
And it also seems that it can't compile with sdl2 2.0.20: https://github.com/haskell-game/sdl2/issues/245

**Comment by dpwiz** [comment]
I merged some polling [fix](https://github.com/haskell-game/sdl2/pull/242), please try with sdl2 master.

**Comment by Mikolaj** [comment]
I've retried the windows CI (it uses sdl2 master branch) and it still doesn't build: https://ci.appveyor.com/project/Mikolaj/lambdahack/build/job/mun11rbmig1cb575

I can't test if it builds on Linux and whether it works once built. @aloaf: can you?

**Comment by aloaf** [comment]
it builds, but now instead of not recognizing input at all, it completely stops responding after any input.

**Comment by Mikolaj** [comment]
Oh dear. Was that with version 2.5.3.2 of sdl2?
